services:
  - type: web
    name: classroom-interaction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k eventlet -w 1 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0

